### ISSUE TITLE
Cannot build on 32 bit system

### ISSUE THREAD

**Issue by kriukov** [dpsanders/CRlibm.jl#14]
OS: Debian 8.6 32 bit; julia 0.5.0

Pkg.build("CRlibm") causes multiple instances of the error "PIC register clobbered by ‘ebx’ in ‘asm’", followed by "recipe for target 'test_perf.o' failed". Is there a workaround?

**Comment by dpsanders** [comment]
I have no idea what that is about. You might want to ask on the Julia Discourse forum.

**Comment by dpsanders** [comment]
Can you please post (e.g. as a gist) the entire output of `Pkg.build("CRlibm")`?

**Comment by dpsanders** [comment]
Also just try changing to the `~/.julia/v0.5/CRlibm/deps/src/crlibm-1.0beta4/` directory and doing `./configure` and then `make`

**Comment by kriukov** [comment]
julia> Pkg.build("CRlibm")
INFO: Building CRlibm
Working in /home/kriukov/.julia/v0.5/CRlibm/deps/src/crlibm-1.0beta4
Working in /home/kriukov/.julia/v0.5/CRlibm/deps/src/crlibm-1.0beta4
Making all in scs_lib
Making all in .
Making all in tests
In file included from test_perf.c:16:0:
test_perf.c: In function ‘test_without_cache’:
../scs_lib/tests/tbx_timing.h:55:9: error: PIC register clobbered by 
‘ebx’ in ‘asm’
          __asm__ __volatile__(             \
          ^
test_perf.c:203:4: note: in expansion of macro ‘TBX_GET_TICK’
     TBX_GET_TICK(t1);
     ^
../scs_lib/tests/tbx_timing.h:55:9: error: PIC register clobbered by 
‘ebx’ in ‘asm’
          __asm__ __volatile__(             \
          ^
test_perf.c:208:4: note: in expansion of macro ‘TBX_GET_TICK’
     TBX_GET_TICK(t2);
     ^
../scs_lib/tests/tbx_timing.h:55:9: error: PIC register clobbered by 
‘ebx’ in ‘asm’
          __asm__ __volatile__(             \
          ^
test_perf.c:210:4: note: in expansion of macro ‘TBX_GET_TICK’
     TBX_GET_TICK(t1);
     ^
../scs_lib/tests/tbx_timing.h:55:9: error: PIC register clobbered by 
‘ebx’ in ‘asm’
          __asm__ __volatile__(             \
          ^
test_perf.c:215:4: note: in expansion of macro ‘TBX_GET_TICK’
     TBX_GET_TICK(t2);
     ^
test_perf.c: In function ‘test_worst_case’:
../scs_lib/tests/tbx_timing.h:55:9: error: PIC register clobbered by 
‘ebx’ in ‘asm’
          __asm__ __volatile__(             \
          ^
test_perf.c:314:4: note: in expansion of macro ‘TBX_GET_TICK’
     TBX_GET_TICK(t1);
     ^
../scs_lib/tests/tbx_timing.h:55:9: error: PIC register clobbered by 
‘ebx’ in ‘asm’
          __asm__ __volatile__(             \
          ^
test_perf.c:319:4: note: in expansion of macro ‘TBX_GET_TICK’
     TBX_GET_TICK(t2);
     ^
../scs_lib/tests/tbx_timing.h:55:9: error: PIC register clobbered by 
‘ebx’ in ‘asm’
          __asm__ __volatile__(             \
          ^
test_perf.c:321:4: note: in expansion of macro ‘TBX_GET_TICK’
     TBX_GET_TICK(t1);
     ^
../scs_lib/tests/tbx_timing.h:55:9: error: PIC register clobbered by 
‘ebx’ in ‘asm’
          __asm__ __volatile__(             \
          ^
test_perf.c:326:4: note: in expansion of macro ‘TBX_GET_TICK’
     TBX_GET_TICK(t2);
     ^
test_perf.c: In function ‘main’:
../scs_lib/tests/tbx_timing.h:55:9: error: PIC register clobbered by 
‘ebx’ in ‘asm’
          __asm__ __volatile__(             \
          ^
test_perf.c:560:5: note: in expansion of macro ‘TBX_GET_TICK’
      TBX_GET_TICK(t1);
      ^
../scs_lib/tests/tbx_timing.h:55:9: error: PIC register clobbered by 
‘ebx’ in ‘asm’
          __asm__ __volatile__(             \
          ^
test_perf.c:561:5: note: in expansion of macro ‘TBX_GET_TICK’
      TBX_GET_TICK(t2);
      ^
Makefile:346: recipe for target 'test_perf.o' failed
make[2]: *** [test_perf.o] Error 1
Makefile:553: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
Makefile:393: recipe for target 'all' failed
make: *** [all] Error 2
===========================================================================[ 
ERROR: CRlibm 
]============================================================================

LoadError: failed process: Process(`make -s V=0`, ProcessExited(2)) [2]
while loading /home/kriukov/.julia/v0.5/CRlibm/deps/build.jl, in 
expression starting on line 29

========================================================================================================================================================================

============================================================================[ 
BUILD ERRORS 
]============================================================================

WARNING: CRlibm had build errors.

  - packages with build errors remain installed in /home/kriukov/.julia/v0.5
  - build the package(s) and all dependencies with `Pkg.build("CRlibm")`
  - build a single package by running its `deps/build.jl` script

========================================================================================================================================================================

David P. Sanders wrote:

**Comment by kriukov** [comment]
I did ./configure and make, all ended successfully. But then the problem 
persists:

julia> using ValidatedNumerics
INFO: Recompiling stale cache file 
/home/kriukov/.julia/lib/v0.5/ValidatedNumerics.ji for module 
ValidatedNumerics.
INFO: Call `CRlibm.setup() to define correctly-rounded functions`
WARNING: CRlibm is falling back to use MPFR; it will have
         the same functionality, but with slower execution.
         This is currently the only option on Windows.
CRlibm will shadow MPFR.


David P. Sanders wrote:

**Comment by dpsanders** [comment]
I have no idea if this problem still persists. Closing but feel free to reopen.
