### ISSUE TITLE
Tag new version

### ISSUE THREAD

**Issue by lbenet** [dpsanders/CRlibm.jl#23]
What about tagging a new version?

**Comment by dpsanders** [comment]
Any objection to releasing 1.0?

**Comment by lbenet** [comment]
Actually, I have; I was checking if it is compatible in Julia 1.0, and seems it is not; see https://travis-ci.org/JuliaDiff/TaylorSeries.jl/jobs/414905896#L518. I suggest that we solve this problem before 1.0.

**Comment by dpsanders** [comment]
That is because it's still using the previous tagged version.

**Comment by dpsanders** [comment]
Just tagged 0.7.

**Comment by lbenet** [comment]
Excelent! Thanks a lot!
