### ISSUE TITLE
Build error with Julia 1.0.2

### ISSUE THREAD

**Issue by arbenede** [dpsanders/CRlibm.jl#29]
I am getting the following error with Julia 1.0.2 under Windows 10:

(v1.0) pkg> build IntervalArithmetic
  Building CRlibm → `C:\Users\arbenede\.julia\packages\CRlibm\Qp9lA\deps\build.log`
┌ Error: Error building `CRlibm`:
│ ERROR: LoadError: UndefVarError: warn not defined
│ Stacktrace:
│  [1] top-level scope at C:\Users\arbenede\.julia\packages\CRlibm\Qp9lA\deps\build.jl:7
│  [2] include at .\boot.jl:317 [inlined]
│  [3] include_relative(::Module, ::String) at .\loading.jl:1044
│  [4] include(::Module, ::String) at .\sysimg.jl:29
│  [5] include(::String) at .\client.jl:392
│  [6] top-level scope at none:0
│ in expression starting at C:\Users\arbenede\.julia\packages\CRlibm\Qp9lA\deps\build.jl:6
└ @ Pkg.Operations C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.0\Pkg\src\Operations.jl:1097

**Comment by arbenede** [comment]
I just verified that the open pull request will fix this issue.

**Comment by dpsanders** [comment]
I have tagged a new version with #28 included. 
Thanks!

**Comment by dpsanders** [comment]
(Version 0.7.1)
