### ISSUE TITLE
Can't Build

### ISSUE THREAD

**Issue by arnavs** [dpsanders/CRlibm.jl#30]
Keep seeing this error. 

```
(v1.2) pkg> build CRlibm
  Building CRlibm → `~/.julia/packages/CRlibm/2S9DB/deps/build.log`
┌ Error: Error building `CRlibm`: 
│ configure: error: newly created file is older than distributed files!
│ Check your system clock
│ ERROR: LoadError: failed process: Process(`./configure --silent 'CFLAGS=-fpic -w'`, ProcessExited(1)) [1]
│ 
│ Stacktrace:
│  [1] pipeline_error at ./process.jl:813 [inlined]
│  [2] #run#536(::Bool, ::typeof(run), ::Cmd) at ./process.jl:728
│  [3] run(::Cmd) at ./process.jl:726
│  [4] top-level scope at /Users/arnavsood/.julia/packages/CRlibm/2S9DB/deps/build.jl:23
│  [5] include_relative(::Module, ::String) at /Applications/Julia-1.2.app/Contents/Resources/julia/lib/julia/sys.dylib:?
│  [6] include(::Module, ::String) at ./Base.jl:31
│  [7] include(::String) at ./client.jl:431
│  [8] top-level scope at none:5
│ in expression starting at /Users/arnavsood/.julia/packages/CRlibm/2S9DB/deps/build.jl:23
│ Working in /Users/arnavsood/.julia/packages/CRlibm/2S9DB/deps/src/crlibm-1.0beta4
└ @ Pkg.Operations /Applications/Julia-1.2.app/Contents/Resources/julia/share/julia/stdlib/v1.2/Pkg/src/backwards_compatible_isolation.jl:647
```

My information is 

```
julia> versioninfo()
Julia Version 1.2.0
Commit c6da87ff4b (2019-08-20 00:03 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.6.0)
  CPU: Intel(R) Xeon(R) W-2140B CPU @ 3.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
```

**Comment by dpsanders** [comment]
Weird. I have the same system and don't see this. 
Presumably you've tried `]rm CRlibm` and reinstalling it?

(And have you "checked your system clock", as it suggests?)

**Comment by arnavs** [comment]
Thanks @dpsanders for quick reply. 

Tried flushing the cache, but I'll do so again. 

I tried also `touch`ing all the files in the directory it mentioned (someone on stackoverflow suggested this). I'm not really sure what to do for the system clock. It looks correct to me...

**Comment by arnavs** [comment]
No luck after a second flush of the package.

**Comment by dpsanders** [comment]
This seems to be a problem unique to your system and does seem to have something to do with the clock? I don't think there's anything I can do.

It could also be that there's some logic in the `configure` file that is wrong. But we just provide a wrapper around that -- I don't understand much of what's going on at that level to be honest. (And I don't know anything about `configure` files.)

**Comment by arnavs** [comment]
I precompiled it again and it said something about falling back to something called `MPFR` or something like that? dunno. 

Anyways, sounds good. Will close this issue then.
