### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by mfherbst** [dpsanders/CRlibm.jl#35]
In order to tackle the second aspect I mentioned in https://github.com/JuliaIntervals/IntervalArithmetic.jl/issues/336, I would suggest to release a new version of CRLibm with the recent patch #31, such that it can be pinned in IntervalArithmetic.

**Comment by dpsanders** [comment]
0.8 is now released containing #31. Thanks!

**Comment by mfherbst** [comment]
Thanks!
