### ISSUE TITLE
generic julia installation (Pkg.instantiate()) fails on MacOS

### ISSUE THREAD

**Issue by kalmarek** [dpsanders/CRlibm.jl#40]
This comes from one of users of my package, so details are sparse, sorry for this.

<img width="1118" alt="Zrzut ekranu 2020-10-20 o 20 45 47" src="https://user-images.githubusercontent.com/1666118/96691230-f0b5f700-1384-11eb-919a-35d027b73b68.png">
 
is the issue known/something to be done about it?

**Comment by dpsanders** [comment]
It looks like they don't have a C compiler installed / configured correctly?

We should move to distributing precompiled binaries instead. (I think there is an open issue about this.)

**Comment by kalmarek** [comment]
yes there is: #26 

yes, env/project was the first experience with coding for him, so I doubt he installed gcc/clang on a whim before :)

**Comment by dpsanders** [comment]
I thought there was a way of failing gracefully if a compiler wasn't installed.

If there isn't then there should be.

**Comment by kalmarek** [comment]
I guess you do fail gracefully (the code run correctly later on), but the error was scary (for him) and I guess easy to fix with jlls

**Comment by dpsanders** [comment]
Ah OK. But yes it's a scary error and not clear that you should just try again!

**Comment by dpsanders** [comment]
This should be fixed now!
