### ISSUE TITLE
Include source code?

### ISSUE THREAD

**Issue by dpsanders** [dpsanders/CRlibm.jl#5]
Should we include the CRlibm source code as part of the package, rather than downloading it?

**Comment by dpsanders** [comment]
I don't know what the license implications are.

**Comment by dpsanders** [comment]
Travis was just unable to download the package (apparently the server is down). So this would definitely be a good idea.

**Comment by ghost** [comment]
Excuse me, I hope the CRlibm to be available for  windows.

INFO: Installing CRlibm v0.2.3
INFO: Installing Calculus v0.1.15
INFO: Installing FixedSizeArrays v0.2.1
INFO: Installing ForwardDiff v0.2.0
INFO: Installing NaNMath v0.2.1
INFO: Installing ValidatedNumerics v0.4.3
INFO: Building CRlibm
===============================[ ERROR: CRlibm ]================================

LoadError: Package not currently available on Windows
while loading C:\Users\123.julia\v0.4\CRlibm\deps\build.jl, in expression starting on line 15

================================[ BUILD ERRORS ]================================

WARNING: CRlibm had build errors.

packages with build errors remain installed in C:\Users\123.julia\v0.4
build the package(s) and all dependencies with Pkg.build("CRlibm")
build a single package by running its deps/build.jl script
INFO: Package database updated
INFO: METADATA is out-of-date — you may not have the latest version of ValidatedNumerics
INFO: Use Pkg.update() to get the latest versions of your packages

**Comment by dpsanders** [comment]
The `CRlibm` functionality is currently not available on Windows. 
In the latest version there is a wrapper in the package to use MPFR instead.
However, I do not have access to a Windows machine to test this on.

Could you try doing `Pkg.update()` to get the latest version? 
And please continue to report errors so that we can get this working on Windows. Thanks.

**Comment by ghost** [comment]
Thank you for your quick reply.Though there still are some warnings, but it finally works.

**WARNING: CRlibm not properly installed. Try running Pkg.build("CRlibm") to fix it. Falling back to use MPFR. Note that Windows is not yet supported.**
INFO: Recompiling stale cache file C:\Users\123.julia\lib\v0.4\FixedSizeArrays.ji for module FixedSizeArrays.
**WARNING: could not import LinAlg._chol! into FixedSizeArrays**
INFO: Recompiling stale cache file C:\Users\123.julia\lib\v0.4\ValidatedNumerics.ji for module ValidatedNumerics.
**WARNING: CRlibm not properly installed. Try running Pkg.build("CRlibm") to fix it. Falling back to use MPFR. Note that Windows is not yet supported.**
**WARNING: New definition** 
    promote_rule(Type{#A<:Real}, Type{ForwardDiff.Dual{#N<:Any, #B<:Real}}) at C:\Users\123.julia\v0.4\ForwardDiff\src\dual.jl:149
is ambiguous with: 
    promote_rule(Type{ValidatedNumerics.Interval{#T<:Real}}, Type{#S<:Real}) at C:\Users\123.julia\v0.4\ValidatedNumerics\src\intervals\conversion.jl:9.
To fix, define 
    promote_rule(Type{ValidatedNumerics.Interval{#T<:Real}}, Type{ForwardDiff.Dual{#N<:Any, #B<:Real}})
before the new definition.
**WARNING: New definition** 
    promote_rule(Type{#A<:Real}, Type{ForwardDiff.Dual{#N<:Any, #B<:Real}}) at C:\Users\123.julia\v0.4\ForwardDiff\src\dual.jl:149
is ambiguous with: 
    promote_rule(Type{ValidatedNumerics.DecoratedInterval{#T<:Real}}, Type{#S<:Real}) at C:\Users\123.julia\v0.4\ValidatedNumerics\src\decorations\intervals.jl:76.
To fix, define 
    promote_rule(Type{ValidatedNumerics.DecoratedInterval{#T<:Real}}, Type{ForwardDiff.Dual{#N<:Any, #B<:Real}})
before the new definition.
**WARNING: New definition** 
    promote_rule(Type{ValidatedNumerics.Interval{#T<:Real}}, Type{#S<:Real}) at C:\Users\123.julia\v0.4\ValidatedNumerics\src\intervals\conversion.jl:9
is ambiguous with: 
    promote_rule(Type{#A<:Real}, Type{ForwardDiff.Dual{#N<:Any, #B<:Real}}) at C:\Users\123.julia\v0.4\ForwardDiff\src\dual.jl:149.
To fix, define 
    promote_rule(Type{ValidatedNumerics.Interval{#T<:Real}}, Type{ForwardDiff.Dual{#N<:Any, #B<:Real}})
before the new definition.
**WARNING: New definition** 
    promote_rule(Type{ValidatedNumerics.DecoratedInterval{#T<:Real}}, Type{#S<:Real}) at C:\Users\123.julia\v0.4\ValidatedNumerics\src\decorations\intervals.jl:76
is ambiguous with: 
    promote_rule(Type{#A<:Real}, Type{ForwardDiff.Dual{#N<:Any, #B<:Real}}) at C:\Users\123.julia\v0.4\ForwardDiff\src\dual.jl:149.
To fix, define 
    promote_rule(Type{ValidatedNumerics.DecoratedInterval{#T<:Real}}, Type{ForwardDiff.Dual{#N<:Any, #B<:Real}})
before the new definition.

**Comment by Vectornaut** [comment]
I was able to work around this issue by replacing the broken LibForge link with an Internet Archive snapshot. To ensure people can keep using `ValidatedNumerics` until this is fixed properly, I've put in a [pull request](https://github.com/dpsanders/CRlibm.jl/pull/12) for my modified build script as a **temporary** workaround.

Although there may be licensing subtleties I'm not aware of, it seems to me that CRlibm's GPL 2.0 license allows the Internet Archive, like anyone else, to distribute copies of the source code. For that reason, I don't suppose downloading the source from the Internet Archive would be more problematic than downloading it from the developers' page.

**Comment by dpsanders** [comment]
Closed by #11
